version: "3"

networks:
    traefik_net:
        external: true

volumes:
    app:

services:
    db:
        image: mysql:8.0.33
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./.dbdata:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3307:3306"
        networks:
            - traefik_net
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
                APP_PATH_CONTAINER: ${APP_PATH_CONTAINER}
        environment:
            - PHP_IDE_CONFIG=serverName=grapheme
        volumes:
            - ${APP_PATH}:${APP_PATH_CONTAINER}
        networks:
            - traefik_net
    nginx:
        build:
            context: ./nginx
        environment:
            VIRTUAL_HOST: cp.pushkinopark.ru
        volumes:
            - ${APP_PATH}:${APP_PATH_CONTAINER}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ppark.rule=Host(`cp.pushkinopark.ru`)"
            - "traefik.http.routers.ppark.entrypoints=websecure"
            - "traefik.http.routers.ppark.tls.certresolver=myresolver"
        networks:
            - traefik_net
        env_file:
            - .env
