version: "3"

networks:
    app:

volumes:
    app:

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./.dbdata:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - app
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
                APP_PATH_CONTAINER: ${APP_PATH_CONTAINER}
        environment:
            - PHP_IDE_CONFIG=serverName=grapheme
        volumes:
            - ${APP_PATH}:${APP_PATH_CONTAINER}
        networks:
            - app
        extra_hosts:
            - host.docker.internal:host-gateway
    nginx:
        build:
            context: ./nginx
        volumes:
            - ${APP_PATH}:${APP_PATH_CONTAINER}
        ports:
            - "80:80"
        networks:
            - app
        env_file:
            - .env
